http.host: "0.0.0.0"
xpack.monitoring.elasticsearch.hosts: [ "http://elasticsearch:9200" ]
xpack.monitoring.elasticsearch.username: "elastic" 
xpack.monitoring.elasticsearch.password: "changeme"
xpack.management.enabled: true
xpack.management.elasticsearch.hosts: "http://elasticsearch:9200/"
xpack.management.elasticsearch.username: "elastic"
xpack.management.elasticsearch.password: "changeme"
xpack.management.logstash.poll_interval: 1s
xpack.management.pipeline.id: ["beats", "http", "bano"]
